// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: cargoToMgr.proto

package cargoToMgr

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CargoInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IP    string  `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Port  string  `protobuf:"bytes,2,opt,name=Port,proto3" json:"Port,omitempty"`
	TSize float64 `protobuf:"fixed64,3,opt,name=TSize,proto3" json:"TSize,omitempty"`
	Lat   float64 `protobuf:"fixed64,4,opt,name=Lat,proto3" json:"Lat,omitempty"`
	Lon   float64 `protobuf:"fixed64,5,opt,name=Lon,proto3" json:"Lon,omitempty"`
}

func (x *CargoInfo) Reset() {
	*x = CargoInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cargoToMgr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CargoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CargoInfo) ProtoMessage() {}

func (x *CargoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cargoToMgr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CargoInfo.ProtoReflect.Descriptor instead.
func (*CargoInfo) Descriptor() ([]byte, []int) {
	return file_cargoToMgr_proto_rawDescGZIP(), []int{0}
}

func (x *CargoInfo) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *CargoInfo) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *CargoInfo) GetTSize() float64 {
	if x != nil {
		return x.TSize
	}
	return 0
}

func (x *CargoInfo) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *CargoInfo) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Ack string `protobuf:"bytes,2,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cargoToMgr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_cargoToMgr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_cargoToMgr_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Ack) GetAck() string {
	if x != nil {
		return x.Ack
	}
	return ""
}

var File_cargoToMgr_proto protoreflect.FileDescriptor

var file_cargoToMgr_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x54, 0x6f, 0x4d, 0x67, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x54, 0x6f, 0x4d, 0x67, 0x72, 0x22, 0x69,
	0x0a, 0x09, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x12, 0x12, 0x0a, 0x04, 0x50,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05,
	0x54, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x03, 0x4c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x4c, 0x6f, 0x6e, 0x22, 0x27, 0x0a, 0x03, 0x41, 0x63, 0x6b,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61,
	0x63, 0x6b, 0x32, 0x4a, 0x0a, 0x0d, 0x72, 0x70, 0x63, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x54, 0x6f,
	0x4d, 0x67, 0x72, 0x12, 0x39, 0x0a, 0x0d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54,
	0x6f, 0x4d, 0x67, 0x72, 0x12, 0x15, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x54, 0x6f, 0x4d, 0x67,
	0x72, 0x2e, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0f, 0x2e, 0x63, 0x61,
	0x72, 0x67, 0x6f, 0x54, 0x6f, 0x4d, 0x67, 0x72, 0x2e, 0x41, 0x63, 0x6b, 0x22, 0x00, 0x42, 0x2d,
	0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x72, 0x6d,
	0x61, 0x64, 0x61, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2f, 0x72,
	0x70, 0x63, 0x2f, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x54, 0x6f, 0x4d, 0x67, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cargoToMgr_proto_rawDescOnce sync.Once
	file_cargoToMgr_proto_rawDescData = file_cargoToMgr_proto_rawDesc
)

func file_cargoToMgr_proto_rawDescGZIP() []byte {
	file_cargoToMgr_proto_rawDescOnce.Do(func() {
		file_cargoToMgr_proto_rawDescData = protoimpl.X.CompressGZIP(file_cargoToMgr_proto_rawDescData)
	})
	return file_cargoToMgr_proto_rawDescData
}

var file_cargoToMgr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cargoToMgr_proto_goTypes = []interface{}{
	(*CargoInfo)(nil), // 0: cargoToMgr.CargoInfo
	(*Ack)(nil),       // 1: cargoToMgr.Ack
}
var file_cargoToMgr_proto_depIdxs = []int32{
	0, // 0: cargoToMgr.rpcCargoToMgr.RegisterToMgr:input_type -> cargoToMgr.CargoInfo
	1, // 1: cargoToMgr.rpcCargoToMgr.RegisterToMgr:output_type -> cargoToMgr.Ack
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cargoToMgr_proto_init() }
func file_cargoToMgr_proto_init() {
	if File_cargoToMgr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cargoToMgr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CargoInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cargoToMgr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cargoToMgr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cargoToMgr_proto_goTypes,
		DependencyIndexes: file_cargoToMgr_proto_depIdxs,
		MessageInfos:      file_cargoToMgr_proto_msgTypes,
	}.Build()
	File_cargoToMgr_proto = out.File
	file_cargoToMgr_proto_rawDesc = nil
	file_cargoToMgr_proto_goTypes = nil
	file_cargoToMgr_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RpcCargoToMgrClient is the client API for RpcCargoToMgr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RpcCargoToMgrClient interface {
	RegisterToMgr(ctx context.Context, in *CargoInfo, opts ...grpc.CallOption) (*Ack, error)
}

type rpcCargoToMgrClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcCargoToMgrClient(cc grpc.ClientConnInterface) RpcCargoToMgrClient {
	return &rpcCargoToMgrClient{cc}
}

func (c *rpcCargoToMgrClient) RegisterToMgr(ctx context.Context, in *CargoInfo, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/cargoToMgr.rpcCargoToMgr/RegisterToMgr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcCargoToMgrServer is the server API for RpcCargoToMgr service.
type RpcCargoToMgrServer interface {
	RegisterToMgr(context.Context, *CargoInfo) (*Ack, error)
}

// UnimplementedRpcCargoToMgrServer can be embedded to have forward compatible implementations.
type UnimplementedRpcCargoToMgrServer struct {
}

func (*UnimplementedRpcCargoToMgrServer) RegisterToMgr(context.Context, *CargoInfo) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterToMgr not implemented")
}

func RegisterRpcCargoToMgrServer(s *grpc.Server, srv RpcCargoToMgrServer) {
	s.RegisterService(&_RpcCargoToMgr_serviceDesc, srv)
}

func _RpcCargoToMgr_RegisterToMgr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CargoInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcCargoToMgrServer).RegisterToMgr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cargoToMgr.rpcCargoToMgr/RegisterToMgr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcCargoToMgrServer).RegisterToMgr(ctx, req.(*CargoInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _RpcCargoToMgr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cargoToMgr.rpcCargoToMgr",
	HandlerType: (*RpcCargoToMgrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterToMgr",
			Handler:    _RpcCargoToMgr_RegisterToMgr_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cargoToMgr.proto",
}
