// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: taskToCargoMgr.proto

package taskToCargoMgr

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RequesterInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat       float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon       float64 `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Size      int64   `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	NReplicas int64   `protobuf:"varint,4,opt,name=nReplicas,proto3" json:"nReplicas,omitempty"`
	AppID     string  `protobuf:"bytes,5,opt,name=appID,proto3" json:"appID,omitempty"`
}

func (x *RequesterInfo) Reset() {
	*x = RequesterInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskToCargoMgr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequesterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequesterInfo) ProtoMessage() {}

func (x *RequesterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_taskToCargoMgr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequesterInfo.ProtoReflect.Descriptor instead.
func (*RequesterInfo) Descriptor() ([]byte, []int) {
	return file_taskToCargoMgr_proto_rawDescGZIP(), []int{0}
}

func (x *RequesterInfo) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *RequesterInfo) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *RequesterInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *RequesterInfo) GetNReplicas() int64 {
	if x != nil {
		return x.NReplicas
	}
	return 0
}

func (x *RequesterInfo) GetAppID() string {
	if x != nil {
		return x.AppID
	}
	return ""
}

type Cargos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IPs   []string `protobuf:"bytes,1,rep,name=IPs,proto3" json:"IPs,omitempty"`
	Ports []string `protobuf:"bytes,2,rep,name=Ports,proto3" json:"Ports,omitempty"`
}

func (x *Cargos) Reset() {
	*x = Cargos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskToCargoMgr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cargos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cargos) ProtoMessage() {}

func (x *Cargos) ProtoReflect() protoreflect.Message {
	mi := &file_taskToCargoMgr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cargos.ProtoReflect.Descriptor instead.
func (*Cargos) Descriptor() ([]byte, []int) {
	return file_taskToCargoMgr_proto_rawDescGZIP(), []int{1}
}

func (x *Cargos) GetIPs() []string {
	if x != nil {
		return x.IPs
	}
	return nil
}

func (x *Cargos) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

var File_taskToCargoMgr_proto protoreflect.FileDescriptor

var file_taskToCargoMgr_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x4d, 0x67, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x6f, 0x43, 0x61,
	0x72, 0x67, 0x6f, 0x4d, 0x67, 0x72, 0x22, 0x7b, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x61, 0x70, 0x70, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x44, 0x22, 0x30, 0x0a, 0x06, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x49, 0x50, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x49, 0x50, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x50, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x50, 0x6f, 0x72, 0x74, 0x73, 0x32, 0x5c, 0x0a, 0x11, 0x72, 0x70, 0x63, 0x54, 0x61, 0x73, 0x6b,
	0x54, 0x6f, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x4d, 0x67, 0x72, 0x12, 0x47, 0x0a, 0x0c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x12, 0x1d, 0x2e, 0x74, 0x61, 0x73,
	0x6b, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x4d, 0x67, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x16, 0x2e, 0x74, 0x61, 0x73, 0x6b,
	0x54, 0x6f, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x4d, 0x67, 0x72, 0x2e, 0x43, 0x61, 0x72, 0x67, 0x6f,
	0x73, 0x22, 0x00, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x41, 0x72, 0x6d, 0x61, 0x64, 0x61, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x73, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x6f, 0x43, 0x61,
	0x72, 0x67, 0x6f, 0x4d, 0x67, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_taskToCargoMgr_proto_rawDescOnce sync.Once
	file_taskToCargoMgr_proto_rawDescData = file_taskToCargoMgr_proto_rawDesc
)

func file_taskToCargoMgr_proto_rawDescGZIP() []byte {
	file_taskToCargoMgr_proto_rawDescOnce.Do(func() {
		file_taskToCargoMgr_proto_rawDescData = protoimpl.X.CompressGZIP(file_taskToCargoMgr_proto_rawDescData)
	})
	return file_taskToCargoMgr_proto_rawDescData
}

var file_taskToCargoMgr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_taskToCargoMgr_proto_goTypes = []interface{}{
	(*RequesterInfo)(nil), // 0: taskToCargoMgr.RequesterInfo
	(*Cargos)(nil),        // 1: taskToCargoMgr.Cargos
}
var file_taskToCargoMgr_proto_depIdxs = []int32{
	0, // 0: taskToCargoMgr.rpcTaskToCargoMgr.RequestCargo:input_type -> taskToCargoMgr.RequesterInfo
	1, // 1: taskToCargoMgr.rpcTaskToCargoMgr.RequestCargo:output_type -> taskToCargoMgr.Cargos
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_taskToCargoMgr_proto_init() }
func file_taskToCargoMgr_proto_init() {
	if File_taskToCargoMgr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_taskToCargoMgr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequesterInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskToCargoMgr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cargos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_taskToCargoMgr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taskToCargoMgr_proto_goTypes,
		DependencyIndexes: file_taskToCargoMgr_proto_depIdxs,
		MessageInfos:      file_taskToCargoMgr_proto_msgTypes,
	}.Build()
	File_taskToCargoMgr_proto = out.File
	file_taskToCargoMgr_proto_rawDesc = nil
	file_taskToCargoMgr_proto_goTypes = nil
	file_taskToCargoMgr_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RpcTaskToCargoMgrClient is the client API for RpcTaskToCargoMgr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RpcTaskToCargoMgrClient interface {
	RequestCargo(ctx context.Context, in *RequesterInfo, opts ...grpc.CallOption) (*Cargos, error)
}

type rpcTaskToCargoMgrClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcTaskToCargoMgrClient(cc grpc.ClientConnInterface) RpcTaskToCargoMgrClient {
	return &rpcTaskToCargoMgrClient{cc}
}

func (c *rpcTaskToCargoMgrClient) RequestCargo(ctx context.Context, in *RequesterInfo, opts ...grpc.CallOption) (*Cargos, error) {
	out := new(Cargos)
	err := c.cc.Invoke(ctx, "/taskToCargoMgr.rpcTaskToCargoMgr/RequestCargo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcTaskToCargoMgrServer is the server API for RpcTaskToCargoMgr service.
type RpcTaskToCargoMgrServer interface {
	RequestCargo(context.Context, *RequesterInfo) (*Cargos, error)
}

// UnimplementedRpcTaskToCargoMgrServer can be embedded to have forward compatible implementations.
type UnimplementedRpcTaskToCargoMgrServer struct {
}

func (*UnimplementedRpcTaskToCargoMgrServer) RequestCargo(context.Context, *RequesterInfo) (*Cargos, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestCargo not implemented")
}

func RegisterRpcTaskToCargoMgrServer(s *grpc.Server, srv RpcTaskToCargoMgrServer) {
	s.RegisterService(&_RpcTaskToCargoMgr_serviceDesc, srv)
}

func _RpcTaskToCargoMgr_RequestCargo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequesterInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcTaskToCargoMgrServer).RequestCargo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskToCargoMgr.rpcTaskToCargoMgr/RequestCargo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcTaskToCargoMgrServer).RequestCargo(ctx, req.(*RequesterInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _RpcTaskToCargoMgr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "taskToCargoMgr.rpcTaskToCargoMgr",
	HandlerType: (*RpcTaskToCargoMgrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestCargo",
			Handler:    _RpcTaskToCargoMgr_RequestCargo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "taskToCargoMgr.proto",
}
