// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: cargoToCargo.proto

package cargoToCargo

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ReplicaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName   string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileBuffer []byte `protobuf:"bytes,2,opt,name=fileBuffer,proto3" json:"fileBuffer,omitempty"`
	FileSize   int64  `protobuf:"varint,3,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	FileType   string `protobuf:"bytes,4,opt,name=fileType,proto3" json:"fileType,omitempty"`
	AppID      string `protobuf:"bytes,5,opt,name=appID,proto3" json:"appID,omitempty"`
}

func (x *ReplicaData) Reset() {
	*x = ReplicaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cargoToCargo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaData) ProtoMessage() {}

func (x *ReplicaData) ProtoReflect() protoreflect.Message {
	mi := &file_cargoToCargo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaData.ProtoReflect.Descriptor instead.
func (*ReplicaData) Descriptor() ([]byte, []int) {
	return file_cargoToCargo_proto_rawDescGZIP(), []int{0}
}

func (x *ReplicaData) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ReplicaData) GetFileBuffer() []byte {
	if x != nil {
		return x.FileBuffer
	}
	return nil
}

func (x *ReplicaData) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ReplicaData) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *ReplicaData) GetAppID() string {
	if x != nil {
		return x.AppID
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack string `protobuf:"bytes,2,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cargoToCargo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_cargoToCargo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_cargoToCargo_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetAck() string {
	if x != nil {
		return x.Ack
	}
	return ""
}

var File_cargoToCargo_proto protoreflect.FileDescriptor

var file_cargoToCargo_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x54, 0x6f, 0x43, 0x61, 0x72,
	0x67, 0x6f, 0x22, 0x97, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x44, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x44, 0x22, 0x17, 0x0a, 0x03,
	0x41, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x61, 0x63, 0x6b, 0x32, 0x53, 0x0a, 0x0f, 0x72, 0x70, 0x63, 0x43, 0x61, 0x72, 0x67,
	0x6f, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x12, 0x40, 0x0a, 0x0e, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x49, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x12, 0x19, 0x2e, 0x63, 0x61, 0x72,
	0x67, 0x6f, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x11, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x54, 0x6f, 0x43,
	0x61, 0x72, 0x67, 0x6f, 0x2e, 0x41, 0x63, 0x6b, 0x22, 0x00, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x72, 0x6d, 0x61, 0x64, 0x61, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x63,
	0x61, 0x72, 0x67, 0x6f, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_cargoToCargo_proto_rawDescOnce sync.Once
	file_cargoToCargo_proto_rawDescData = file_cargoToCargo_proto_rawDesc
)

func file_cargoToCargo_proto_rawDescGZIP() []byte {
	file_cargoToCargo_proto_rawDescOnce.Do(func() {
		file_cargoToCargo_proto_rawDescData = protoimpl.X.CompressGZIP(file_cargoToCargo_proto_rawDescData)
	})
	return file_cargoToCargo_proto_rawDescData
}

var file_cargoToCargo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cargoToCargo_proto_goTypes = []interface{}{
	(*ReplicaData)(nil), // 0: cargoToCargo.ReplicaData
	(*Ack)(nil),         // 1: cargoToCargo.Ack
}
var file_cargoToCargo_proto_depIdxs = []int32{
	0, // 0: cargoToCargo.rpcCargoToCargo.StoreInReplica:input_type -> cargoToCargo.ReplicaData
	1, // 1: cargoToCargo.rpcCargoToCargo.StoreInReplica:output_type -> cargoToCargo.Ack
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cargoToCargo_proto_init() }
func file_cargoToCargo_proto_init() {
	if File_cargoToCargo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cargoToCargo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplicaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cargoToCargo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cargoToCargo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cargoToCargo_proto_goTypes,
		DependencyIndexes: file_cargoToCargo_proto_depIdxs,
		MessageInfos:      file_cargoToCargo_proto_msgTypes,
	}.Build()
	File_cargoToCargo_proto = out.File
	file_cargoToCargo_proto_rawDesc = nil
	file_cargoToCargo_proto_goTypes = nil
	file_cargoToCargo_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RpcCargoToCargoClient is the client API for RpcCargoToCargo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RpcCargoToCargoClient interface {
	StoreInReplica(ctx context.Context, in *ReplicaData, opts ...grpc.CallOption) (*Ack, error)
}

type rpcCargoToCargoClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcCargoToCargoClient(cc grpc.ClientConnInterface) RpcCargoToCargoClient {
	return &rpcCargoToCargoClient{cc}
}

func (c *rpcCargoToCargoClient) StoreInReplica(ctx context.Context, in *ReplicaData, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/cargoToCargo.rpcCargoToCargo/StoreInReplica", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcCargoToCargoServer is the server API for RpcCargoToCargo service.
type RpcCargoToCargoServer interface {
	StoreInReplica(context.Context, *ReplicaData) (*Ack, error)
}

// UnimplementedRpcCargoToCargoServer can be embedded to have forward compatible implementations.
type UnimplementedRpcCargoToCargoServer struct {
}

func (*UnimplementedRpcCargoToCargoServer) StoreInReplica(context.Context, *ReplicaData) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreInReplica not implemented")
}

func RegisterRpcCargoToCargoServer(s *grpc.Server, srv RpcCargoToCargoServer) {
	s.RegisterService(&_RpcCargoToCargo_serviceDesc, srv)
}

func _RpcCargoToCargo_StoreInReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcCargoToCargoServer).StoreInReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cargoToCargo.rpcCargoToCargo/StoreInReplica",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcCargoToCargoServer).StoreInReplica(ctx, req.(*ReplicaData))
	}
	return interceptor(ctx, in, info, handler)
}

var _RpcCargoToCargo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cargoToCargo.rpcCargoToCargo",
	HandlerType: (*RpcCargoToCargoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreInReplica",
			Handler:    _RpcCargoToCargo_StoreInReplica_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cargoToCargo.proto",
}
